### ISSUE TITLE
master file not found

### ISSUE THREAD

**Issue by yemrekula0748** [lhandal/crypto-trading-bot#1]
master file not found, do not work docker

**Comment by yemrekula0748** [comment]
manifest for freqtradeorg/freqtrade:master not found: manifest unknown: manifest unknown

**Comment by mkjawadi** [comment]
I faced the exact same error while running `docker-compose run --rm freqtrade trade -s BB_RSI` command.

`manifest for freqtradeorg/freqtrade:master not found: manifest unknown: manifest unknown`

![image](https://user-images.githubusercontent.com/32951993/118404468-3c652080-b688-11eb-8cf5-9b2fe02080b9.png)

**Comment by mistokes18** [comment]
i have the same problem any fixes?

**Comment by lhandal** [comment]
Please refer to [Freqtrade's Github](https://github.com/freqtrade/freqtrade) for the latest updates.
