### ISSUE TITLE
modified for btc

### ISSUE THREAD

**Issue by imperialjoy** [lhandal/crypto-trading-bot#2]
Hi,

Thanks for writing this clear and easy to setup bot, it seems to do ok in dry run mode when the market is going up which is nice to see.

How can I modify this to use BTC as the stake currency instead of USDT?  What parameters would you change besides the stake currency and the pairs?

**Comment by lhandal** [comment]
Hello @imperialjoy ,

Glad you found the bot useful. In order to change the stake currency you have to modify line 3 on the [config.json](https://github.com/lhandal/crypto-trading-bot/blob/master/user_data/config.json) file:

"stake_currency": "USDT" --> "stake_currency": "BTC",
